### ISSUE TITLE
Writing and finishing succeeds without errors but archive is corrupted

### ISSUE THREAD

**Issue by thedrow** [alexcrichton/tar-rs#167] opened 2018-10-07 19:35 UTC
I have the following code:
```rust
#[macro_use]
extern crate log;
extern crate stderrlog;
extern crate tar;
extern crate tempfile;
extern crate walkdir;

use std::path::Path;
use std::fs::File;
use walkdir::WalkDir;
use tar::Builder;

fn open_file(path: &Path) -> Option<File> {
    return match File::open(path) {
        Ok(f) => Some(f),
        Err(e) => {
            warn!("There was a problem opening {}: {:?}", path.display(), e);
            None
        }
    }
}

struct Packager
{
    tar_builder: Builder<File>
}

impl Packager {

    fn new() -> Packager {
        let tempfile = tempfile::tempfile().unwrap();
        let tar_builder = Builder::new(tempfile);

        Packager {
            tar_builder: tar_builder
        }
    }

    fn append_file(&mut self, path: &Path, file: &mut File) {
        match self.tar_builder.append_file(path, file) {
            Ok(_) => info!("Appended {} to package.", path.display()),
            Err(e) => warn!("An error occured while appending {} to the package: {:?}", path.display(), e)
        }
    }

    fn create_baseline(mut self) -> Option<File> {
        for entry in WalkDir::new("/proc/sys").into_iter().filter_map(|e| e.ok()).filter(|e| !e.file_type().is_dir()) {
            let relative_path = entry.path().strip_prefix("/").unwrap();

            match open_file(entry.path()) {
                Some(f) => {
                    let mut f = f;
                    self.append_file(relative_path, &mut f)
                }
                None => info!("Skipping...")
            }
        }

        match self.tar_builder.into_inner() {
            Ok(file) => {
                info!("Finished building the baseline package!");
                Some(file)
            },
            Err(e) => {
                error!("An error occured while building the baseline package: {:?}", e);
                None
            }
        }
    }
}

fn main() {
    stderrlog::new().module(module_path!()).verbosity(4).init().unwrap();
    let packager = Packager::new();

    info!("Creating baseline package...");
    let file = packager.create_baseline();

    // Testing code ahead
    match file {
        Some(file) => {
            use tar::Archive;
            let mut a = Archive::new(file);

            for f in a.entries().unwrap() {
                // Make sure there wasn't an I/O error
                let mut f = f.unwrap();

                // Inspect metadata about the file
                println!("{:?}", f.header().path().unwrap());
                println!("{}", f.header().size().unwrap());
            }
        }
        None => panic!("????")
    }
}
```

You can compile it on any Linux system using the following dependencies:
```toml
[package]
name = "testcase"

[dependencies]
tar = "^0.4"
tempfile = "^3.0"
walkdir = "^2.2"
stderrlog = "^0.4"
log = "^0.4"
```

I have done everything as documented and yet, I still get the following error when I attempt to read the archive:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("failed to read entire block") }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/result.rs:782
  10: testcase::main
             at src/main.rs:86
  11: std::rt::lang_start::{{closure}}
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

I'm not sure how to minimize this test case.
Attempting to open the tarball using other software fail as well.

**Comment by thedrow** [comment] 2018-10-08 10:04
As it turns out, the file descriptor returned by `into_inner()` cannot be read.

However the following:
```rust
    let file = File::open("test.tar").unwrap();

    use tar::Archive;
    let mut a = Archive::new(file);

    for f in a.entries().unwrap() {
        // Make sure there wasn't an I/O error
        let mut f = f.unwrap();

        // Inspect metadata about the file
        println!("{:?}", f.header().path().unwrap());
        println!("{}", f.header().size().unwrap());
    }
```
Errors with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("numeric field was not a number:  when getting cksum for 1\n") }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/result.rs:782
  10: infraboost_agent::main
             at src/main.rs:88
  11: std::rt::lang_start::{{closure}}
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

This happens when I try to create a tar from the `/etc` folder as well only much later:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: StringError("numeric field was not a number: 8125744k when getting cksum for sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0\nproc /proc proc rw,nosuid,nodev,noexec,relatime") }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libcore/result.rs:782
  10: infraboost_agent::main
             at src/main.rs:88
  11: std::rt::lang_start::{{closure}}
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /tmp/rust-20180926-12043-1n132yg/rustc-1.29.1-src/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

**Comment by thedrow** [comment] 2018-10-08 15:47
I think I see the problem, I have some files which cannot be read due to `Input/Output errors`.
We first write the header of the file and then we write the contents of the file into the tarball.
If copying the contents fail, we are left with a header without a file.
The relevant code is at https://github.com/alexcrichton/tar-rs/blob/master/src/builder.rs#L298

Perhaps we should read the the data into a buffer first and only than copy it if reading succeeded?

**Comment by alexcrichton** [comment] 2018-10-08 16:08
Interesting, thanks for the report! I agree yeah that if you want to handle errors the error handling needs to be a little different here. I'd recommend using `truncate` and/or otherwise truncating the contents if an error happens on any function call. While buffering data is possible this library in general attempts to buffer as little as possible

**Comment by thedrow** [comment] 2018-10-08 17:30
So the only solution is truncating the entire tar file and re-doing everything without the file that caused the error?
That's silly.
Maybe we could introduce a buffered API?

**Comment by alexcrichton** [comment] 2018-10-08 17:33
No my thinking was that before each operation you'd get the current file's position. If that operation fails, you'd truncate the file to that previous position. That way you don't need to redo all your work, but you can effectively erase all possible work that could have happened on the fallible API.

**Comment by thedrow** [comment] 2018-10-08 17:52
On the files I get "Input/Output" errors from I am able to call `f.seek(Seek::FromStart(1))` so that's not a solution.
But rolling back and rewriting might help. I don't think I know how to implement that.

**Comment by alexcrichton** [comment] 2018-10-08 17:54
With typical files you'll typically seek from the current position by 0 to get the current position. After that if you have a `File` you'd use truncate. Alternatively you can encode the tar archive into memory and bypass the filesystem entirely.

In any case though it looks like the underlying bug here was discovered, so I'm going to close this. I'd be fine though having a PR documenting how to recover from errors!

**Closed by alexcrichton** 2018-10-08 17:54 UTC

**Comment by alexcrichton** [comment] 2018-10-09 16:39
Sorry I don't have time right now to dig in and debug this as well. If you can narrow it down though to something that's reproducible which looks like a bug in the `tar` crate we can reopen!
